# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3Lf2kWjKqPPjqfiCAbMSQNqvNFI-57z
"""

# vif test 1 - using pandas
import numpy as np
import pandas as pd
import seaborn as sns

iris = sns.load_dataset('iris')

iris_cor = iris.corr()
iris_vif = pd.DataFrame(np.linalg.inv(iris.corr().values), index = iris_cor.index, columns=iris_cor.columns)
iris_vif.round(2)

# vif test 2 - using pandas
import pandas as pd
import numpy as np

a = [1, 1, 2, 3, 4]
b = [2, 2, 3, 2, 1]
c = [4, 6, 7, 8, 9]
d = [4, 3, 4, 5, 4]

df = pd.DataFrame({'a':a,'b':b,'c':c,'d':d})
df_cor = df.corr()
vif = pd.DataFrame(np.linalg.inv(df.corr().values), index = df_cor.index, columns=df_cor.columns)
vif

# vif test 3 - using statmodels
from statsmodels.stats.outliers_influence import variance_inflation_factor
import numpy as np

a = [1, 1, 2, 3, 4]
b = [2, 2, 3, 2, 1]
c = [4, 6, 7, 8, 9]
d = [4, 3, 4, 5, 4]

ck = np.column_stack([a, b, c, d])

vif = [variance_inflation_factor(ck,i) for i in range (ck.shape[1])]
print(vif)